apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asg-lifecycle-manager
  labels:
    chart: "asg-lifecycle-manager-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: asg-lifecycle-manager
    spec:
      imagePullSecrets:
      - name: docker-registry-logicmonitor-net
      serviceAccountName: asg-lifecycle-manager
      containers:
      - name: asg-lifecycle-manager
        image: "logicmonitor/k8s-asg-lifecycle-manager:latest"
        imagePullPolicy: Always
        env:
        - name: NODEMAN_AWS_REGION
          value: "ap-northeast-1"
        - name: NODEMAN_AWS_SQS_QUEUE_URL
          value: "https://sqs.ap-northeast-1.amazonaws.com/393024300663/k8s-asg-lifecycle-manager-feed"
        - name: NODEMAN_DEBUG
          value: "true"
        ports:
        - containerPort: 8080
