apiVersion: v1
kind: Service
metadata:
  name: asg-lifecycle-manager
  labels:
    chart: "asg-lifecycle-manager-0.1.0"
spec:
  type: ClusterIP
  selector:
    app: asg-lifecycle-manager
  ports:
  - name: metrics
    port: 8080
